### ISSUE TITLE
Grid excel export as blob 

### ISSUE THREAD

**Issue by Hellogark** [syncfusion/ej2-javascript-ui-controls#120] opened 2021-07-22 18:56 UTC
I'm working with ejs-angular  and cordova.
I'm trying to export a grid to excel but i can't get the blob file to save it in a mobile device.
I do this to get the blob from pdf export 
```
 public firstGridPdfExport: Promise<Object>; 
 public pivotGridObj: PivotView;
this.firstGridPdfExport = this.pivotGridObj.grid.pdfExport({}, true);

 this.firstGridPdfExport.then(async (pdfData: any) => {
            let {blobData} = await pdfData.save();
              this.saveMobileFile('Export.pdf',blobData,'application/pdf'); 
          });
```

But excel export doesn't return a blob, only returns an object with styles array and worksheets array.

This is how i generate de file
```
 this.firstGridExcelExport = this.pivotGridObj.grid.excelExport({}, null,null,true);
          this.firstGridExcelExport.then(async (excelData: any) => {
            //excelData returns   {  styles: [...], worksheets: [...] }
              let {blobData} = await excelData.save(); //Doesn't have a save function
              this.saveMobileFile('Export.xls',blobData,'application/xls'); 
          });
```
Is there a way to get the blob file? Because i've been searching and the blob generation happens internaly when the excel is beign generated.
I'm using  ej2-angular-pivotview 17.4.43

**Comment by ManiRam94** [comment] 2021-07-28 07:05
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/TEMPKA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/TEMPKA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/TEMPKA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal style='vertical-align:baseline'>Hi Customer,<o:p></o:p></p>

<p class=MsoNormal style='vertical-align:baseline'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='vertical-align:baseline'>Kindly use the “<b>excelExportComplete</b>”
event to get blob data while excel exporting. Please refer the following code
example.<o:p></o:p></p>

<p class=MsoNormal style='vertical-align:baseline'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='vertical-align:baseline'><b>Code Example:<o:p></o:p></b></p>



excelExpComplete(args: ExcelExportCompleteArgs) {       args.promise.then((e: { blobData: Blob }) => {         console.log(e.blobData);       });     }     ngOnInit(): void {       document.getElementById('export').onclick = () => {         this.pivotObj.grid.excelExportComplete = this.excelExpComplete.bind(this);         this.pivotObj.excelExport(null, null, null, true);       };     }
--




<p class=MsoNormal style='vertical-align:baseline'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='vertical-align:baseline'>Meanwhile, we have prepared
a sample for your reference.<o:p></o:p></p>

<p class=MsoNormal style='vertical-align:baseline'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='vertical-align:baseline'><b>Sample:</b> <a
href="https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackblitz.com%2Fedit%2Fangular-9v14aq%3Ffile%3Dapp.component.ts&amp;data=04%7C01%7Cmanikandan.murugesan%40syncfusion.com%7Ca095e8d97d0348550a5608d95195731a%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637630524580328914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=JD8FyOcH0%2FiRpYoFr1TfmFkibr%2BAXI21HvoE4fCgY0Y%3D&amp;reserved=0">https://stackblitz.com/edit/angular-9v14aq?file=app.component.ts</a><o:p></o:p></p>

<p class=MsoNormal style='vertical-align:baseline'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='vertical-align:baseline'>Please let us know if you
need further assistance with this.<o:p></o:p></p>

<p class=MsoNormal style='vertical-align:baseline'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='vertical-align:baseline'>Regards,<o:p></o:p></p>

<p class=MsoNormal style='vertical-align:baseline'>Manikandan<o:p></o:p></p>


</body>

</html>

**Comment by Hellogark** [comment] 2021-08-19 18:12
indeed excelExportComplete works in stackblitz but is deprecated and is not working for me, i'm getting
` {name: "excelExportComplete"}` as args and i'm getting this error `Uncaught (in promise): TypeError: Cannot read property 'then' of undefined`

**Comment by ManiRam94** [comment] 2021-08-20 10:05
Hi Customer,

We have checked the reported problem and we are unable to reproduce it at our end. Please refer to the following sample.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/pivot-1102289041

If the problem still exists, kindly reproduce the problem in the provided sample and revert us (or) send your sample that replicating the problem. This would be helpful for us to investigate the reported problem at our end and provide the solution at the earliest.

Regards,
Manikandan

**Comment by syncsiva** [comment] 2022-02-02 12:23
Close the issue since has not had any activity for 3 months.

**Closed by syncsiva** 2022-02-02 12:23 UTC
Labels: data-grid
