### ISSUE TITLE
export/import ical, problem with exception on reccurring appointment

### ISSUE THREAD

**Issue by Ikaer** [syncfusion/ej2-javascript-ui-controls#118] opened 2021-07-15 06:53 UTC
Hi,

I think there is a bug with the export/import when a reccuring rule is used with some exception. 
Here are my steps to reproduce:
on https://ej2.syncfusion.com/documentation/schedule/exporting/#exporting-calendar-events-as-ics-file
switch to month view and create a weekly event "my_event"
![image](https://user-images.githubusercontent.com/7936075/125742203-f2b2d78c-a130-4b22-a2a9-338d02db7667.png)
Edit one of the event, but not the series and update the title for "my_event_exception"
On the calendar, everything is ok:

![image](https://user-images.githubusercontent.com/7936075/125742375-9b13c24e-16c1-4a15-a518-2dcfe82646e9.png)

Then export the ical file, and try to reupload it in https://ej2.syncfusion.com/documentation/schedule/exporting/#import-events-from-other-calendars 
the exception seem to exist aside the reccuring event and not as part of the event
![image](https://user-images.githubusercontent.com/7936075/125742546-38add8be-ab28-4ed8-b0be-7b62298e17f6.png)

**Comment by Nevitha-Ravi** [comment] 2021-07-16 06:47
@Ikaer  - Greetings from Syncfusion Support.

We could replicate the reported problem ‘exception on recurring appointment not handled on ics export file’ and confirmed this as defect at our end. We have logged the bug reported which can be tracked through the following link.
https://www.syncfusion.com/feedback/27072/export-import-ical-problem-with-exception-on-reccurring-appointment

The fix will be included in our weekly patch release scheduled on end of July 2021.We would appreciate your patience until then.

Regards,
Nevitha.

**Comment by Nevitha-Ravi** [comment] 2021-07-28 12:53
@Ikaer  - Thanks for being patience.

We are glad to announce that our weekly patch release v19.2.49 has been rolled out successfully. The reported bug with exporting and importing recurring appointment with exception has been fixed in this release. As a result, we recommend you upgrade to the latest version of our Syncfusion package to avail this fix.

https://ej2.syncfusion.com/javascript/documentation/release-notes/19.2.49/?type=all#schedule
https://www.syncfusion.com/feedback/27072/export-import-ical-problem-with-exception-on-reccurring-appointment

Kindly check the reported defect in the latest version and get back to us if you need any further assistance. 

Regards,
Nevitha

**Comment by rajendranr-5483** [comment] 2021-10-15 09:49
Hi @Ikaer 

We are closing this thread now since there is no recent activity. 

Regards,
Rajendran R

**Closed by rajendranr-5483** 2021-10-15 09:49 UTC
Labels: schedule
