### ISSUE TITLE
Scheduler Render.prototype.refreshDataManager could be invoked before this.parent.activeView is set

### ISSUE THREAD

**Issue by cxspxr** [syncfusion/ej2-javascript-ui-controls#97] opened 2021-02-16 09:02 UTC
In my project during react scheduler rendering there could be a change in a store from what I feed my scheduler. And by that point on some occasions `this.parent.activeView` is `undefined`, thus throwing `startDate` of undefined. I will open a PR with a if-return, but I guess it's better for you guys to check why `activeView` could be not set. I can't share my react code here, but I am setting literally `currentView="Week"` for the scheduler component **+** `isSelected` option on `ViewDirective` and it works well but sometimes the scheduler crashes, when there is `refreshDataManager` invocation before `this.parent.activeView` is set on scheduler component first time rendering. 

https://github.com/syncfusion/ej2-javascript-ui-controls/blob/7814a9c312db9761ed26bec43389ceb980bb008b/controls/schedule/src/schedule/renderer/renderer.ts#L135

**Comment by Balasubramanian-Sattanathan** [comment] 2021-02-18 14:49
Dear customer,

Greetings from Syncfusion Support.

We have checked your reported problem at our end and could reproduce it. So we logged the below bug report. The fix will be included in our weekly patch release scheduled on March 2, 2021 and would appreciate your valuable patience until then. You can track the status by using the below link

https://www.syncfusion.com/feedback/22596/getting-console-error-while-refresh-the-scheduler-datamanager

Regards,
Balasubramanian S

**Comment by cxspxr** [comment] 2021-03-04 12:13
@ajithr the issue still persist, because `refreshDataManager` is not only invoked from `Renderer.render` but also e.g. from `ScheduleComponent.Schedule.propertyChangeAction` and possibly in other places. I guess it is better to move `activeView` check directly to the `refreshDataManager`.

```
renderer.js:164 Uncaught (in promise) TypeError: Cannot read property 'startDate' of undefined
    at Render.refreshDataManager (renderer.js:164)
    at ScheduleComponent.Schedule.propertyChangeAction (schedule.js:1492)
    at ScheduleComponent.Schedule.onPropertyChanged (schedule.js:1472)
    at ScheduleComponent.Base.dataBind (base.js:132)
    at ScheduleComponent.Component.dataBind (component.js:269)
    at ScheduleComponent.Base.setProperties (base.js:72)
    at ScheduleComponent.ComponentBase.refreshProperties (component-base.js:160)
    at ScheduleComponent.ComponentBase.updateProperties (component-base.js:149)
    at ScheduleComponent.ComponentBase.shouldComponentUpdate (component-base.js:101)
    at checkShouldComponentUpdate (react-dom.development.js:12730)
```

**Comment by maheshtps** [comment] 2021-03-17 13:31
Hi Everyone,

We are glad to announce that our weekly release in version 18.4.48 has been rolled out successfully. In that release, we have fixed the reported issue.  So, we suggest you upgrade our Syncfusion packages to avail of the fix on your end.

Release notes: 
https://ej2.syncfusion.com/react/documentation/release-notes/18.4.48/?type=all#schedule

Could you please check and get back to us, if you need any further assistance on this.

Regards,
Mahesh

**Closed** 2021-07-20 04:37 UTC
Labels: bug, schedule

**Comment by rajendranr-5483** [comment] 2021-07-20 04:40
We are closing this issue since there is no recent activity. Feel free to reopen the issue and update your comments for the reinvestigation.
