### ISSUE TITLE
get Error when using "insert special character" with "inlineMode"

### ISSUE THREAD

**Issue by yalnjooj** [syncfusion/ej2-javascript-ui-controls#121] opened 2021-07-30 19:38 UTC
**works fine when using "insert special character" without "inlineMode"**
![ex1](https://user-images.githubusercontent.com/29558023/127568635-ed609d8b-cccd-4cca-bbcc-5daea97cb921.png)

**get Error when using "insert special character" with "inlineMode"**
![ex2](https://user-images.githubusercontent.com/29558023/127568737-46639df7-5fd1-4c8a-9ae3-5e0c63319936.png)

**full example in stackblitz**
https://stackblitz.com/edit/angular-ewbx5u?file=app.component.html

**Comment by gunasekar-kuppusamy** [comment] 2021-08-02 11:01
Hi yalnjooj,

We have validated the reported query "get Error when using "insert special character" with "inlineMode" and we were able to reproduce this error from our end.

On RichTextEditor initial loading, the toolbar element is not rendered in the DOM.
So inline RichTextEditor sample try to find the element on initial loading and failed then return the script error.

We have resolved this error by using the quickToolbarOpen event instead of created event.

We also modified the sample for your reference.
**Sample**: https://stackblitz.com/edit/angular-ewbx5u-snb594?file=package.json

Please check the sample and let us know if the solution helps

Regards,
Gunasekar

**Comment by yalnjooj** [comment] 2021-08-03 14:33
thank you for help, yes it works fine in stackblitz.com
but when trying to click Ω button in my local project that what happen:
![image](https://user-images.githubusercontent.com/29558023/128009986-d7733a18-dc6f-409e-98d5-6f65fd7a1cb0.png)

Provide different object: in stackblitz.com
![image](https://user-images.githubusercontent.com/29558023/128026163-719057bc-f626-4fdb-997d-f811159a12c4.png)

and my local project: 
![image](https://user-images.githubusercontent.com/29558023/128026317-2635e909-37f6-493e-8845-cf407e47e985.png)

thanks for help agin...

**Comment by IndrajithSrinivasan** [comment] 2021-12-23 13:41
We suspect the object reference, is not initialized properly. Check the below code blocks for reference.

**App.component.html**

`<ejs-dialog #Dialog /> `

**App.component.ts**

```
@ViewChild('Dialog')
public dialogObj: Dialog;

```

If you are still facing the reported issue, can you share us a minimal issue reproducible project to validate further on this reported issue ?

**Comment by syncsiva** [comment] 2022-02-02 12:23
Close the issue since has not had any activity for one month.

**Closed by syncsiva** 2022-02-02 12:23 UTC
Labels: rich-text-editor
